### PR TITLE
Update row 510 - Project Edge in the title

### PR DESCRIPTION
**Pull request by KuraudoXS**
Proposing update of title to include Project Edge for easier research among fans

### CODE REVIEW

**Review by julianxhokaxhiu — APPROVED** [review]
LGTM

**Comment by eve-atum** [comment]
I'm ok with it, though it's a little misleading since there's a couple of other non-PE fields in there (e.g. faulked's subway cars)

**Comment by KuraudoXS** [comment]
Added missing authors.

**Comment by wturner859** [comment]
changing the name won't do much until the name is also changed in the mod.xml. Once an update (md1stin) is released, then I can do both at the same time.

**Pull request closed without merging**
