### PR TITLE
Update qhimm.xml

### PR DESCRIPTION
**Pull request by bradhowlett**
I believe I have everything right. I hope

### CODE REVIEW

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
Almost there :) In your `mod.xml` you miss the tag `<ID>` which must the same used here in the catalog ( as it has to match ). This is required to make sure all mods are unique in the catalog and they don't clash by the name. Thanks!

**Comment by bradhowlett** [comment]
> Ok thank you. I will work on that as wellSincerely Brad HowlettOn Nov 22, 2024, at 11:20 AM, Julian Xhokaxhiu ***@***.***> wrote:﻿ @julianxhokaxhiu requested changes on this pull request. Almost there :) In your mod.xml you miss the tag <ID> which must the same used here in the catalog ( as it has to match ). This is required to make sure all mods are unique in the catalog and they don't clash by the name. Thanks! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I added the ID to the mod.xml. I then reuploaded everything. I did change the gdrive ID in my PR to target the new file with the fixed mod.xml.

**Comment by julianxhokaxhiu** [comment]
Thanks, I'm checking the PR but the download of the drive file seems to be the same as before ( and if I try to access it says it doesn't exist ). Did you commit the change to the same branch where you've opened the PR from?

**Comment by bradhowlett** [comment]
Darn. Sorry. I’m trying to learn. No I didn’t but I willSincerely Brad HowlettOn Nov 23, 2024, at 11:12 AM, Julian Xhokaxhiu ***@***.***> wrote:﻿
Thanks, I'm checking the PR but the download of the drive file seems to be the same as before ( and if I try to access it says it doesn't exist ). Did you commit the change to the same branch where you've opened the PR from?

**Comment by bradhowlett** [comment]
I figured out now how to edit and commit. Thank you for you patience and help. Should the GDrive be pointing at my WereXIII folder or just the iro. If it is just the iro then I will fix again
    On Saturday, November 23, 2024 at 11:12:20 AM CST, Julian Xhokaxhiu ***@***.***> wrote:  
 
 


Thanks, I'm checking the PR but the download of the drive file seems to be the same as before ( and if I try to access it says it doesn't exist ). Did you commit the change to the same branch where you've opened the PR from?

**Comment by bradhowlett** [comment]
I created 2 commits today. The first is if the GDrive ID needs to point to my entire mod folder and the second is if it just needs to point to the iro

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Well done :) Merged and tested, all works as intended, thank you and congratulations!

**Pull request merged**
