### PR TITLE
Update qhimm.xml

### PR DESCRIPTION
**Pull request by eve-atum**
We keep talking about getting rid of Remako, let's just finally do it.  Also remove Borderless since FFNx now handles that natively.

### CODE REVIEW

**Comment by KuraudoXS** [comment]
Also remove DrLilo FMV to avoid confusing users. With all due respect, now we have Cosmos FMV.

**Comment by eve-atum** [comment]
I didn't see DrLilo in there, unless it's being called something else?

**Comment by KuraudoXS** [comment]
From line 934.

**Comment by eve-atum** [comment]
I see it now...

**Comment by wturner859** [comment]
Closed for deprecated solution

**Pull request closed without merging**
