### PR TITLE
Update qhimm.xml

### PR DESCRIPTION
**Pull request by bradhowlett**

### CODE REVIEW

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Thank you very much and congratulations on your first contribution! :)

**Comment by bradhowlett** [comment]
Ok I will. Thank you for all the information. I will work on this tonightSincerely Brad HowlettOn Nov 20, 2024, at 10:53 AM, Julian Xhokaxhiu ***@***.***> wrote:﻿
I'm sorry @bradhowlett but I had to revert your change as it breaks the catalog, because I noticed the <ID> tag is not following the spec, it needs to be a GUID. Additionally, downloading your mod I noticed your mod.xml is missing an ID guid as well, which you can get by 7th Heaven itself when you use the Tools -> Catalog/Mod Creation Tool.
Finally, you have a modBU.xml file which is not needed so please delete that one as well.
Make sure you fix all of this and open a new PR to get your mod added back again. Sorry and thanks.

**Comment by bradhowlett** [comment]
I honestly do not know what I am doing. I made a mod and people are asking me to add to the catalog. I will paste what 7H generated but I do not know if it will work. I can send you anything just to add it for me. Otherwise I am outside of my knowledge on coding and cannot make the followers happy in uploading the mod. Please advise. This is what 7H generated:## WereXIII - by Wolfman    <Mod>      <ID>1e3f4894-86bd-4099-ad54-7a2f7dbaa8cf</ID>      <Author>WolfMan Kuroda CMH175 and Leet</Author>      <Link>https://www.nexusmods.com/finalfantasy7/mods/124</Link>  <LatestVersion>        <Link>iros://GDrive/1e3f4894-86bd-4099-ad54-7a2f7dbaa8cf</Link> <Version>3.0</Version>        <ReleaseDate>2014-06-10</ReleaseDate>        <CompatibleGameVersions>All</CompatibleGameVersions>        <PreviewImage></PreviewImage>        <ReleaseNotes/>        <DownloadSize>218.9</DownloadSize> </LatestVersion>      <Name>WereXIII</Name>      <Category>Gameplay</Category>      <Description>IMPORTANT = This Mod must be placed at the top.This project was a long immense project. This project has been unreal. It started June 23rd 2014 and took 3 months. This mod replaces Red XIII, a quadruped Lionish with a full blown kick-ass Lycanthrope. This mod includes the battle model, field model, custom animations, 7 limit breaks, avatar and all casting animations. A lot of people have had hands in on this and I really appreciate it. If you find any problems or bugs or ideas on animation tweaks let me know. :::Thanks:::to those who worked directly on the project and especially CMH175, who I feel ended up more as a co producer than someone who assisted.
CMH175 Leet Jeet Kaldarasha EQ2Alyza Kuroda Jusete And everyone who had suggestions and pointers.And all of the creators of the tools that were used for the project.      </Description>      <Tags></Tags>    </Mod>


    On Wednesday, November 20, 2024 at 12:49:56 PM CST, Brad M Howlett ***@***.***> wrote:  
 
 Ok I will. Thank you for all the information. I will work on this tonight
Sincerely Brad Howlett

On Nov 20, 2024, at 10:53 AM, Julian Xhokaxhiu ***@***.***> wrote:



﻿


I'm sorry @bradhowlett but I had to revert your change as it breaks the catalog, because I noticed the <ID> tag is not following the spec, it needs to be a GUID. Additionally, downloading your mod I noticed your mod.xml is missing an ID guid as well, which you can get by 7th Heaven itself when you use the Tools -> Catalog/Mod Creation Tool.
Finally, you have a modBU.xml file which is not needed so please delete that one as well.

Make sure you fix all of this and open a new PR to get your mod added back again. Sorry and thanks.

**Comment by julianxhokaxhiu** [comment]
Please ask for help and support on Discord if you are in doubt, and come back here once you have something ready to be submitted :) Also feel free to have a look at https://7thheaven.rocks/help/modhelp.html in the meantime. Let's not abuse this PR for support, thank you!

**Comment by bradhowlett** [comment]
Thanks. Will doSincerely Brad HowlettOn Nov 21, 2024, at 5:11 AM, Julian Xhokaxhiu ***@***.***> wrote:﻿
Please ask for help and support on Discord if you are in doubt, and come back here once you have something ready to be submitted :) Also feel free to have a look at https://7thheaven.rocks/help/modhelp.html in the meantime. Let's not abuse this PR for support, thank you!

**Pull request merged**
